package:
  name: panvc3
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ.get('GIT_FULL_HASH', '')) }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '') }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

source:
  path: ..

requirements:
  build:
    - backtrace
    - bzip2 >=1.0.8
    - cmake =3.26.4
    - gcc =12.3.0
    - gengetopt >=2.23
    - gxx =12.3.0
    - libboost =1.82.0
    - libboost-headers =1.82.0
    - libstdcxx-devel_linux-64 =12.3.0
    - m4 >=1.4.18
    - ragel >=6.10
    - sysroot_linux-64 >=2.28
    - zlib >=1.3.1
  run:
    - backtrace
    - bzip2 >=1.0.8
    - libboost =1.82.0
    - libgcc-ng >=12.3.0
    - libstdcxx-ng >=12.3.0
    - libzlib >=1.3.1

about:
  home: https://github.com/tsnorri/panvc3
  license: MIT
  description: "Variant calling using a pan-genomic reference"
