package:
  name: panvc3
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ.get('GIT_FULL_HASH', '')) }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '') }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

source:
  path: ..

requirements:
  build:
    - boost-cpp =1.82.0
    - bzip2 >=1.0.8
    - clang >=16.0.6
    - clangxx >=16.0.6
    - cmake =3.26.4
    - gcc =12.3.0
    - gengetopt >=2.23
    - gxx =12.3.0
#    - libcxx >=16.0.6
    - libstdcxx-devel_linux-64 =12.3.0
    - m4 >=1.4.18
    - ninja =1.11.1
    - ragel >=6.10
    - sysroot_linux-64 >=2.28
    - zlib >=1.2.13
  run:
    - boost-cpp =1.82.0
    - bzip2 >=1.0.8
    - libgcc-ng =12.3.0
    - libstdcxx-ng =12.3.0
    - zlib >=1.2.13

about:
  home: https://github.com/tsnorri/panvc3
  license: MIT
  description: "Variant calling using a pan-genomic reference"
